### ISSUE TITLE
std=c++20 not available

### ISSUE THREAD

**Issue by rolfglei** [kissadamfkut/mora_blinker#1]
Hello,

nice project. I'm a beginner. Some experience on arduino and avr-gcc. 
Will use Your project for starting c++ on attiny-processors...

Having problems with my compiler avr-gcc (GCC) 5.4.0 on Debian sid:
avr-gcc: error: unrecognized command line option ‘-std=c++20’

-std=c++2a doesn't work also.

If i use -std=c++17 there are new issues:
"In file included from fade.cpp:1:0:
timing.hpp:2:18: fatal error: cstdint: Datei oder Verzeichnis nicht gefunden"
and more lines similar. Same for array...

Is there a library I had to install?

Thanks.

**Comment by kissadamfkut** [comment]
Hello!

You should use newer avr-gcc and c++20. My avr-gcc is version 12.2.0

Adam

rolfglei ***@***.***> ezt írta (időpont: 2023. febr. 23., Cs,
10:37):
